### PR TITLE
Reg and Mentor buttons added w/ Mobile scaling

### PR DESCRIPTION
**Pull request by Shikkic**
Done

### CODE REVIEW

**Comment by SriRamanujam** [comment]
Daniel you've forgotten to make the buttons go anywhere lol 

(hint the routes are `/register` and `/mentor`)

**Comment by skeswa** [comment]
This^^^

**Comment by Shikkic** [comment]
Added href values

**Comment by SriRamanujam** [comment]
Daniel. It needs the full link, Daniel. Like `http://owlhacks.com/register`, Daniel. Why do you do this to me Daniel.

**Pull request merged**
