### PR TITLE
Huge Design Overhaul

### PR DESCRIPTION
**Pull request by skeswa**
I recognized some areas that needed design improvements and changed them to my liking. Some things are still a little rough around the edges, but I think its an improvement. @YurkaninRyan I completely gutted the FAQ, but I really like the direction you took us in. You should all critique this before it goes live.

### CODE REVIEW

**Comment by skeswa** [comment]
@YurkaninRyan @CodyJamesCasey @SriRamanujam  @samuelcouch I need this to be reviewed before it goes live.

**Comment by samuelcouch** [comment]
Can't review from work, but will check it later. We should especially be reviewing the content of spelling and grammar errors though before it goes live.

**Comment by CodyJamesCasey** [comment]
I could probably get away with reviewing it within the next hour. I just don't know how to view the changes that you made. Do I have to clone your fork?

**Comment by samuelcouch** [comment]
@CodyJamesCasey This is what you're looking for https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by samuelcouch** [comment]
If you don't have the command line button at the bottom, this is what you want:

```
git checkout -b skeswa-master master
git pull https://github.com/skeswa/owlhacks-site.git master
```

**Comment by CodyJamesCasey** [comment]
First off, this design looks AWESOME.  Great Job!

I checked the spelling and grammar, and everything checks out to me.  On Chrome though the FAQ Questions aren't collapsing for me.  Did you decide to forgo that functionality or is something wrong?  If we do decide to go with just the triple column build then can we align them better?  It's strange to look at and my eyes are instantly drawn to the buttons instead of the questions because they are so large.

I do like the changes to the HTML though much easier to read then looking at an endless abyss of ul and li tags hahaha.

Besides that cracka jack job, old chum!

**Comment by YurkaninRyan** [comment]
That was me by the way didn't check which account I was on le lulz

**Comment by skeswa** [comment]
I opted for the triple column design over the collapsing section design. I just felt like clicking for more information wasn't the right solution to the scroll problem and I wasn't finding any solutions. In any case, I hear you loud and clear with the QA readability - I'll try and diminish the button size a bit, and maybe I'll add some margin.

**Comment by skeswa** [comment]
@YurkaninRyan take a look now (re-pull it).

**Comment by skeswa** [comment]
Ok, I'm just merging this.

**Pull request merged**
